# Generated by Django 5.0 for otp_security with PostgreSQL immutability trigger

import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("channel", models.CharField(choices=[("sms", "SMS"), ("email", "Email")], max_length=10)),
                ("purpose", models.CharField(db_index=True, default="login", max_length=50)),
                ("salt", models.CharField(max_length=64)),
                ("otp_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "otp_security_otprequest",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.BigIntegerField(db_index=True, unique=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("locked", "Locked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject_hash", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("prev_hash", models.CharField(max_length=64)),
                ("block_hash", models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                "db_table": "otp_security_auditblock",
                "ordering": ["index"],
            },
        ),
        migrations.CreateModel(
            name="MerkleAnchor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anchor_date", models.DateField(db_index=True, unique=True)),
                ("root", models.CharField(max_length=64)),
                ("first_index", models.BigIntegerField()),
                ("last_index", models.BigIntegerField()),
                ("block_count", models.PositiveIntegerField()),
                ("tx_hash", models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "otp_security_merkleanchor",
                "ordering": ["-anchor_date"],
            },
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(
                fields=["identifier", "purpose", "is_used", "is_locked", "is_revoked"],
                name="otp_req_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otprequest",
            index=models.Index(fields=["identifier", "purpose", "created_at"], name="otp_req_lookup_idx"),
        ),
        migrations.RunSQL(
            sql="""
            -- PostgreSQL Trigger: Enforce immutable, append-only security for AuditBlock
            CREATE OR REPLACE FUNCTION prevent_auditblock_modification()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'AuditBlock records are strictly append-only. UPDATE and DELETE operations are prohibited.';
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_prevent_auditblock_tamper ON otp_security_auditblock;
            CREATE TRIGGER trg_prevent_auditblock_tamper
            BEFORE UPDATE OR DELETE ON otp_security_auditblock
            FOR EACH ROW
            EXECUTE FUNCTION prevent_auditblock_modification();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_prevent_auditblock_tamper ON otp_security_auditblock;
            DROP FUNCTION IF EXISTS prevent_auditblock_modification();
            """,
        ),
    ]
