import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // General
    brand: "HealNSight",
    tagline: "Secure Telemedicine Platform",
    rolePatient: "Patient (Citizen)",
    roleDoctor: "Certified Doctor",
    roleAdmin: "Administrator",
    dashboard: "Dashboard",
    logout: "Log Out",
    welcome: "Welcome back",
    verified: "Verified",
    nodeConnected: "Security Broker Connected",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    status: "Status",
    actions: "Actions",

    // Auth & Register
    loginTitle: "Secure Professional Log-In",
    registerTitle: "Create Secure Healthcare Account",
    username: "Username",
    password: "Password",
    email: "Email Address",
    phone: "Phone Number",
    role: "System Role",
    nid: "National ID (NID)",
    emergencyContact: "Emergency Contact (Name & Phone)",
    address: "Home Address",
    bmdc: "BMDC Registration No.",
    specialty: "Medical Specialization",
    hospital: "Hospital/Clinic Affiliation",
    fees: "Consultation Fee (BDT)",
    enterPlatform: "Enter Platform",
    submitRegister: "Submit Registration",
    alreadyRegistered: "Already registered? Log in",
    newMember: "New member? Register as Citizen or Doctor",
    orgCode: "Organization Credentials Code (Admin Only)",
    identityUpload: "Identity Verification Document",
    certUpload: "BMDC Certificate / Degree Upload",
    kycSubmission: "KYC Verification Upload",
    restrictedAdmin: "Admin registration is restricted. Enter organization credentials.",
    invalidAdminCode: "Invalid administration validation code.",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    encIndicator: "Data protected using TLS 1.3 & AES-256 GCM encryption.",
    welcomePatient: "Welcome back, Patient",
    welcomeDoctor: "Welcome back, Doctor",
    welcomeAdmin: "Welcome back, Administrator",
    descPatientLogin: "Access appointments, prescriptions, consultations, and health records.",
    descDoctorLogin: "Manage consultations, patient records, prescriptions, and schedules.",
    descAdminLogin: "Monitor platform activity, compliance, security logs, and user management.",
    secE2ee: "End-to-End Encrypted Communication",
    secCrypto: "Cryptography Protected Medical Records",
    secConsent: "Consent-Based Access Control",
    secConsult: "Secure Real-Time Consultation",
    secKyc: "KYC Verified Users",
    secCompliance: "Regulatory Compliance Ready",
    roleCardPatientSubtitle: "Personal healthcare access",
    roleCardDoctorSubtitle: "Consultation management",
    roleCardAdminSubtitle: "System administration",
    selectRolePrompt: "Please select one role to continue",


    // Patient Dashboard
    vitalsOverview: "Personal Vitals Summary",
    heartRate: "Heart Rate",
    waterIntake: "Water Intake",
    sleepTracker: "Sleep Tracker",
    upcomingAppt: "Upcoming Appointments",
    bookNewAppt: "Schedule Doctor",
    quickActions: "Quick Actions",
    startLiveChat: "Start Live Chat",
    videoRoom: "Video Room",
    phoneSetup: "Phone Setup",
    chooseSpecialist: "Choose Specialist",
    allDoctors: "All Doctors",
    scheduleDetails: "Schedule Details",
    consultationMode: "Consultation Mode",
    selectDate: "Select Date",
    selectTime: "Select Time Slot",
    symptomsReason: "Symptoms/Reason for Consultation",
    submitRequest: "Submit Consultation Request",
    emptyAppt: "No upcoming appointments scheduled.",
    rating: "Rating",
    fee: "Fee",

    // Medical Records
    encryptedRecords: "Encrypted Health Records",
    clinicalIndex: "Encrypted Clinical Index",
    addNewRecord: "Encrypt New Health Record",
    recordCategory: "Record Category",
    recordData: "Report Data (Encrypted at Rest)",
    writeLedger: "Secure Write to Ledger",
    emptyRecords: "No records indexed. Your clinical workspace is secure.",
    aesProtected: "AES-256 Symmetric Protected",
    bloodReport: "Blood Report",
    labResult: "Lab Result",
    clinicalNotes: "Clinical Note",
    diagnosticScan: "Diagnostic Scan",

    // Consent Management
    consentManager: "Consent Manager",
    delegateAccess: "Delegate Clinical Access",
    delegateDesc: "Enforce role-based access security. Explicitly allow registered specialists to inspect your historical health records.",
    selectPhysician: "Select Physician",
    validityDuration: "Consent Validity Duration",
    authorizeKey: "Authorize Key Access",
    activeTokens: "Active Access Tokens",
    emptyConsents: "No consent tokens delegated. Your clinical records are fully isolated.",
    granted: "Granted",
    expires: "Expires",
    revokeAccess: "Revoke Access",
    revoked: "REVOKED",
    oneHour: "1 Hour (Urgent visit)",
    twelveHours: "12 Hours",
    twentyFourHours: "24 Hours (Standard)",
    fortyEightHours: "48 Hours",

    // Doctor Workstation
    docWorkstation: "Physician Workstation",
    dailyQueue: "Patient Consultation Desk",
    incomeOverview: "Earnings Overview",
    availabilityStatus: "Online Availability Status",
    availabilityDesc: "Allows patients to start live audio/video calls.",
    rekeyServer: "Re-Key Cryptography",
    telephonySip: "Twilio Telephony SIP Bridge",
    registered: "REGISTERED",
    approve: "Approve",
    reject: "Reject",
    inspectRecords: "Inspect Patient Records",
    enterClinicalRoom: "Enter Consultation Room",
    writePrescription: "Write Prescription",
    kycStatus: "KYC Verification Status",
    symptoms: "Symptoms",
    diagnosis: "Diagnosis",
    medications: "Medications (JSON Format)",
    instructions: "Instructions",
    savePrescription: "Issue Signed E-Prescription",
    docHome: "Doctor Home",

    // Pharmacy / Delivery
    medicineDelivery: "Medicine Delivery",
    courierLogs: "Courier Shipment Logs",
    orderPrescription: "Order E-Prescribed Medicine",
    deliveryAddress: "Delivery Address (Bangladesh)",
    confirmDispatch: "Confirm Pharmacy Dispatch",
    recipient: "Recipient",
    orderStatus: "Status",
    pack: "Pack Shipment",
    ship: "Ship Order",
    deliver: "Mark Delivered",

    // Admin Controls
    securityAuditLogs: "Security & GDPR Audit Trail",
    timestamp: "Timestamp",
    operator: "Operator",
    auditAction: "Action",
    ipAddress: "IP Address",
    narrative: "Audit Narrative",
    systemHealth: "System Health Metrics",
    kycReviewCenter: "KYC Verification Review Center",
    consentAudit: "Consent Audit Dashboard",
    complianceDoc: "Regulatory Compliance Dashboard",
    fraudMonitoring: "Fraud Detection Monitoring",
    pendingVerifications: "Pending Doctor Registrations",
    verifyDoctorBtn: "Verify BMDC Credentials",
    rejectDoctorBtn: "Deny Credentials",

    // Clinical Room
    clinicalRoom: "Live Clinical Room",
    websocketActive: "E2EE Chat Channel active",
    chatPlaceholder: "Type secure message to room...",
    send: "Send",
    startVideo: "Start Video",
    videoSetupTitle: "HealNsightVideo Room",
    videoSetupDesc: "Prepare for your secure, E2E encrypted consultation. Check your camera and mic before joining.",
    cameraOn: "Camera On",
    micOn: "Mic On",
    joinVideoCall: "Join Secure Video Room",
    encryptedConference: "E2EE Video Conference Live",
    voiceDialpad: "Voice Dialpad",
    sipOffline: "SIP Offline",
    dialerPlaceholder: "Enter phone number...",
    connectPhone: "Connect Phone",
    triggerTwilio: "Trigger Callback Bridge",
    recentLogs: "Call Logs",
    pbxScreen: "PBX Telephony Terminal",

    // Extra Redesign Features
    aiAssistant: "AI Health Assistant",
    aiPlaceholder: "Ask the AI assistant about your symptoms...",
    aiHeader: "AI-Powered Medical Diagnostic Assistant",
    aiDisclaimer: "Disclaimer: This chatbot is AI-driven and does not replace certified professional medical diagnosis.",
    emergencyContactSystem: "Emergency Contact System",
    emergencyAlertBtn: "Trigger SOS Emergency Alert",
    emergencyAlertFired: "SOS EMERGENCY SIGNAL BROADCASTED to nearest hospital and emergency contact!",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    searchDocs: "Advanced Doctor Search"
  },
  bn: {
    // General
    brand: "আরোগ্য সাইট",
    tagline: "নিরাপদ টেলিমেডিসিন প্ল্যাটফর্ম",
    rolePatient: "রোগী (নাগরিক)",
    roleDoctor: "প্রত্যয়িত ডাক্তার",
    roleAdmin: "প্রশাসক",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগ আউট",
    welcome: "স্বাগতম",
    verified: "প্রত্যয়িত",
    nodeConnected: "নিরাপত্তা ব্রোকার সংযুক্ত",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    confirm: "নিশ্চিত করুন",
    status: "অবস্থা",
    actions: "পদক্ষেপ",

    // Auth & Register
    loginTitle: "নিরাপদ পেশাদার লগ-ইন",
    registerTitle: "নিরাপদ স্বাস্থ্যসেবা অ্যাকাউন্ট তৈরি করুন",
    username: "ব্যবহারকারীর নাম",
    password: "পাসওয়ার্ড",
    email: "ইমেইল ঠিকানা",
    phone: "মোবাইল নম্বর",
    role: "সিস্টেমের ভূমিকা",
    nid: "জাতীয় পরিচয়পত্র (NID)",
    emergencyContact: "জরুরী যোগাযোগ (নাম ও ফোন)",
    address: "স্থায়ী ঠিকানা",
    bmdc: "BMDC রেজিস্ট্রেশন নম্বর",
    specialty: "চিকিৎসা বিশেষত্ব",
    hospital: "হাসপাতাল/ক্লিনিক অধিভুক্তি",
    fees: "পরামর্শ ফি (টাকা)",
    enterPlatform: "প্ল্যাটফর্মে প্রবেশ করুন",
    submitRegister: "নিবন্ধন সম্পন্ন করুন",
    alreadyRegistered: "ইতিমধ্যে নিবন্ধিত? লগ ইন করুন",
    newMember: "নতুন সদস্য? নাগরিক বা ডাক্তার হিসেবে নিবন্ধন করুন",
    orgCode: "সংস্থার পরিচয় কোড (শুধুমাত্র অ্যাডমিন)",
    identityUpload: "পরিচয় যাচাইকরণ নথি",
    certUpload: "BMDC সার্টিফিকেট আপলোড",
    kycSubmission: "KYC যাচাইকরণ আপলোড",
    restrictedAdmin: "অ্যাডমিন নিবন্ধন সীমাবদ্ধ। সংস্থার কোড লিখুন।",
    invalidAdminCode: "অবৈধ প্রশাসন কোড।",
    rememberMe: "আমাকে মনে রাখুন",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    encIndicator: "TLS ১.৩ এবং AES-২৫৬ GCM এনক্রিপশন দ্বারা ডেটা সুরক্ষিত।",
    welcomePatient: "স্বাগতম, রোগী",
    welcomeDoctor: "স্বাগতম, ডাক্তার",
    welcomeAdmin: "স্বাগতম, প্রশাসক",
    descPatientLogin: "অ্যাপয়েন্টমেন্ট, প্রেসক্রিপশন, পরামর্শ এবং স্বাস্থ্য রেকর্ড অ্যাক্সেস করুন।",
    descDoctorLogin: "পরামর্শ, রোগীর রেকর্ড, প্রেসক্রিপশন এবং সময়সূচী পরিচালনা করুন।",
    descAdminLogin: "প্ল্যাটফর্ম কার্যকলাপ, সম্মতি, নিরাপত্তা লগ এবং ব্যবহারকারী পরিচালনা করুন।",
    secE2ee: "এন্ড-টু-এন্ড এনক্রিপ্ট করা যোগাযোগ",
    secCrypto: "ক্রিপ্টোগ্রাফি সুরক্ষিত মেডিকেল রেকর্ডস",
    secConsent: "সম্মতি-ভিত্তিক অ্যাক্সেস নিয়ন্ত্রণ",
    secConsult: "নিরাপদ রিয়েল-টাইম পরামর্শ",
    secKyc: "KYC যাচাইকৃত ব্যবহারকারী",
    secCompliance: "নিয়ন্ত্রক সম্মতি প্রস্তুত",
    roleCardPatientSubtitle: "ব্যক্তিগত স্বাস্থ্যসেবা অ্যাক্সেস",
    roleCardDoctorSubtitle: "পরামর্শ ব্যবস্থাপনা",
    roleCardAdminSubtitle: "সিস্টেম প্রশাসন",
    selectRolePrompt: "দয়া করে চালিয়ে যেতে একটি ভূমিকা নির্বাচন করুন",


    // Patient Dashboard
    vitalsOverview: "ব্যক্তিগত ভাইটালস সারাংশ",
    heartRate: "হার্ট রেট",
    waterIntake: "পানি পানের পরিমাণ",
    sleepTracker: "ঘুম ট্র্যাকার",
    upcomingAppt: "আসন্ন অ্যাপয়েন্টমেন্টসমূহ",
    bookNewAppt: "ডাক্তার বুকিং",
    quickActions: "দ্রুত পদক্ষেপ",
    startLiveChat: "লাইভ চ্যাট শুরু করুন",
    videoRoom: "ভিডিও রুম",
    phoneSetup: "ফোন সেটআপ",
    chooseSpecialist: "বিশেষজ্ঞ নির্বাচন করুন",
    allDoctors: "সকল ডাক্তার",
    scheduleDetails: "অ্যাপয়েন্টমেন্টের বিবরণ",
    consultationMode: "পরামর্শের মাধ্যম",
    selectDate: "তারিখ নির্বাচন করুন",
    selectTime: "সময় নির্বাচন করুন",
    symptomsReason: "লক্ষণ/পরামর্শের কারণ",
    submitRequest: "পরামর্শের অনুরোধ জমা দিন",
    emptyAppt: "কোনো আসন্ন অ্যাপয়েন্টমেন্ট নির্ধারিত নেই।",
    rating: "রেটিং",
    fee: "ফি",

    // Medical Records
    encryptedRecords: "এনক্রিপ্ট করা মেডিকেল রেকর্ডস",
    clinicalIndex: "এনক্রিপ্ট করা ক্লিনিক্যাল ইনডেক্স",
    addNewRecord: "নতুন মেডিকেল রেকর্ড এনক্রিপ্ট করুন",
    recordCategory: "রেকর্ডের বিভাগ",
    recordData: "রিপোর্ট ডেটা (সংরক্ষিত অবস্থায় এনক্রিপ্ট করা)",
    writeLedger: "নিরাপদ লেজারে লিখুন",
    emptyRecords: "কোনো রেকর্ড পাওয়া যায়নি। আপনার ক্লিনিক্যাল স্থান সুরক্ষিত।",
    aesProtected: "AES-২৫৬ সিমেট্রিক সুরক্ষিত",
    bloodReport: "রক্তের রিপোর্ট",
    labResult: "ল্যাব পরীক্ষার ফলাফল",
    clinicalNotes: "ক্লিনিক্যাল নোট",
    diagnosticScan: "ডায়াগনস্টিক স্ক্যান",

    // Consent Management
    consentManager: "সম্মতি ম্যানেজার",
    delegateAccess: "ক্লিনিক্যাল অ্যাক্সেস প্রদান করুন",
    delegateDesc: "ভূমিকা-ভিত্তিক অ্যাক্সেস নিরাপত্তা প্রয়োগ করুন। নিবন্ধিত চিকিৎসকদের আপনার মেডিকেল রেকর্ড দেখার অনুমতি দিন।",
    selectPhysician: "চিকিৎসক নির্বাচন করুন",
    validityDuration: "সম্মতির মেয়াদের সময়কাল",
    authorizeKey: "অ্যাক্সেস অনুমোদিত করুন",
    activeTokens: "সক্রিয় অ্যাক্সেস টোকেনসমূহ",
    emptyConsents: "কোনো সম্মতি টোকেন নেই। আপনার মেডিকেল রেকর্ড সম্পূর্ণ নিরাপদ ও আলাদা রয়েছে।",
    granted: "অনুমোদিত",
    expires: "মেয়াদ শেষ হবে",
    revokeAccess: "সম্মতি বাতিল করুন",
    revoked: "বাতিলকৃত",
    oneHour: "১ ঘণ্টা (জরুরী পরিদর্শনের জন্য)",
    twelveHours: "১২ ঘণ্টা",
    twentyFourHours: "২৪ ঘণ্টা (সাধারণ)",
    fortyEightHours: "৪৮ ঘণ্টা",

    // Doctor Workstation
    docWorkstation: "ডাক্তারের ওয়ার্কস্টেশন",
    dailyQueue: "রোগী পরামর্শ ডেস্ক",
    incomeOverview: "উপার্জনের সারাংশ",
    availabilityStatus: "অনলাইন সক্রিয়তার অবস্থা",
    availabilityDesc: "রোগীদের লাইভ অডিও/ভিডিও কল শুরু করার অনুমতি দিন।",
    rekeyServer: "ক্রিপ্টোগ্রাফি রি-কী করুন",
    telephonySip: "টুইলিও টেলিফোনি এসআইপি ব্রিজ",
    registered: "নিবন্ধিত",
    approve: "অনুমোদন করুন",
    reject: "প্রত্যাখ্যান করুন",
    inspectRecords: "রোগীর রেকর্ড পরীক্ষা করুন",
    enterClinicalRoom: "পরামর্শ কক্ষে প্রবেশ করুন",
    writePrescription: "প্রেসক্রিপশন লিখুন",
    kycStatus: "KYC যাচাইকরণের অবস্থা",
    symptoms: "লক্ষণসমূহ",
    diagnosis: "রোগ নির্ণয়",
    medications: "ওষুধসমূহ (JSON বিন্যাসে)",
    instructions: "নির্দেশাবলী",
    savePrescription: "প্রেসক্রিপশন ইস্যু করুন",
    docHome: "ডাক্তার হোম",

    // Pharmacy / Delivery
    medicineDelivery: "ওষুধ বিতরণ",
    courierLogs: "কুরিয়ার শিপমেন্ট লগ",
    orderPrescription: "প্রেসক্রিপশন অনুযায়ী ওষুধ অর্ডার করুন",
    deliveryAddress: "ডেলিভারি ঠিকানা (বাংলাদেশ)",
    confirmDispatch: "ডিসপ্যাচ নিশ্চিত করুন",
    recipient: "প্রাপক",
    orderStatus: "অবস্থা",
    pack: "প্যাকেজিং শুরু করুন",
    ship: "শিপিং করুন",
    deliver: "ডেলিভারি সম্পন্ন করুন",

    // Admin Controls
    securityAuditLogs: "নিরাপত্তা ও জিডিপিআর অডিট ট্রেইল",
    timestamp: "সময়কাল",
    operator: "অপারেটর",
    auditAction: "পদক্ষেপ",
    ipAddress: "আইপি ঠিকানা",
    narrative: "অডিট বিবরণ",
    systemHealth: "সিস্টেম স্বাস্থ্য মেট্রিক্স",
    kycReviewCenter: "KYC যাচাইকরণ পর্যালোচনা কেন্দ্র",
    consentAudit: "সম্মতি অডিট ড্যাশবোর্ড",
    complianceDoc: "নিয়ন্ত্রণ সম্মতি ড্যাশবোর্ড",
    fraudMonitoring: "প্রতারণা সনাক্তকরণ পর্যবেক্ষণ",
    pendingVerifications: "অপেক্ষমান চিকিৎসকদের নিবন্ধন তালিকা",
    verifyDoctorBtn: "BMDC তথ্য যাচাই করুন",
    rejectDoctorBtn: "প্রত্যাখ্যান করুন",

    // Clinical Room
    clinicalRoom: "লাইভ ক্লিনিক্যাল রুম",
    websocketActive: "E2EE চ্যাট চ্যানেল সক্রিয়",
    chatPlaceholder: "কক্ষে সুরক্ষিত বার্তা পাঠান...",
    send: "পাঠান",
    startVideo: "ভিডিও শুরু করুন",
    videoSetupTitle: "আরোগ্য সাইট ভিডিও রুম",
    videoSetupDesc: "আপনার সুরক্ষিত, E2E এনক্রিপ্ট করা পরামর্শের জন্য প্রস্তুত হন। যোগদানের আগে ক্যামেরা ও মাইক পরীক্ষা করুন।",
    cameraOn: "ক্যামেরা অন",
    micOn: "মাইক অন",
    joinVideoCall: "সুরক্ষিত ভিডিও রুমে যোগ দিন",
    encryptedConference: "E2EE ভিডিও কনফারেন্স লাইভ",
    voiceDialpad: "ভয়েস ডায়ালপ্যাড",
    sipOffline: "এসআইপি অফলাইন",
    dialerPlaceholder: "ফোন নম্বর লিখুন...",
    connectPhone: "ফোন কানেক্ট করুন",
    triggerTwilio: "কলব্যাক ব্রিজ চালু করুন",
    recentLogs: "কল লগসমূহ",
    pbxScreen: "PBX টেলিফোনি টার্মিনাল",

    // Extra Redesign Features
    aiAssistant: "এআই স্বাস্থ্য সহকারী",
    aiPlaceholder: "আপনার লক্ষণ সম্পর্কে এআই সহকারীকে জিজ্ঞাসা করুন...",
    aiHeader: "এআই-চালিত স্বাস্থ্য সহায়ক",
    aiDisclaimer: "দাবিত্যাগ: এই চ্যাটবটটি এআই-চালিত এবং কোনো প্রত্যয়িত পেশাদার চিকিৎসা রোগ নির্ণয়ের বিকল্প নয়।",
    emergencyContactSystem: "জরুরী যোগাযোগ ব্যবস্থা",
    emergencyAlertBtn: "জরুরী সংকেত চালু করুন (SOS)",
    emergencyAlertFired: "নিকটবর্তী হাসপাতাল ও আপনার জরুরী পরিচিতিতে জরুরী সংকেত (SOS) পাঠানো হয়েছে!",
    darkMode: "ডার্ক মোড",
    lightMode: "লাইট মোড",
    language: "ভাষা",
    searchDocs: "ডাক্তারদের উন্নত সার্চ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const toggleLanguage = () => {
    setLang(prev => prev === 'en' ? 'bn' : 'en');
  };

  const t = (key) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
