# Generated by Django 6.0.6 on 2026-07-08 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_file', models.TextField(blank=True, help_text='Stored Base64 string of legacy image', null=True)),
                ('previous_data', models.JSONField(default=dict, help_text='Stores vision extraction and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient'], name='api_patient_patient_c27d2f_idx')],
            },
        ),
    ]
