# Generated by Django 6.0.6 on 2026-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blockchainrecord_loginattempt_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainrecord',
            name='anchored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='blockchain_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='blockchain_network',
            field=models.CharField(default='Sepolia Sim', max_length=50),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='blockchain_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='blockchain_status',
            field=models.CharField(default='BLOCKCHAIN_PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='contract_address',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='blockchainrecord',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
