# Generated by Django 6.0.6 on 2026-08-30 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockchainrecord_anchored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonyCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text='E.164 formatted recipient phone number', max_length=30)),
                ('from_phone', models.CharField(blank=True, help_text='Verified Twilio caller number', max_length=30, null=True)),
                ('twilio_call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('mode', models.CharField(choices=[('live', 'Live Twilio Voice PSTN'), ('mock', 'Sandbox Simulation')], default='mock', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephony_calls', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephony_calls', to='api.consultation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
