# Generated by Django 6.0.6 on 2026-09-26 19:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='schedule',
            field=models.JSONField(blank=True, default=api.models.default_doctor_schedule, help_text='Weekly consultation schedule slots'),
        ),
    ]
