# Generated by Django 6.0.6 on 2026-09-27 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_doctorprofile_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Device-reported latitude (-90 to 90)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Device-reported longitude (-180 to 180)', null=True)),
                ('location_accuracy', models.FloatField(blank=True, help_text='Device-reported accuracy in meters', null=True)),
                ('location_available', models.BooleanField(default=False, help_text="Whether the patient's device provided GPS coordinates")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed'), ('SMS_NOT_CONFIGURED', 'SMS Not Configured'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sms_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('NOT_CONFIGURED', 'Not Configured')], default='PENDING', max_length=20)),
                ('twilio_message_sid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
