# Generated by Django 6.0.6 on 2026-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(blank=True, help_text='sms, email, or totp', max_length=20, null=True),
        ),
    ]
