# Generated by Django 6.0.6 on 2026-10-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_mfa_enabled_user_mfa_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_type',
        ),
        migrations.DeleteModel(
            name='EmergencyAlert',
        ),
    ]
