# Generated by Django 6.0.6 on 2026-10-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_mfa_enabled_remove_user_mfa_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='anonymous_session_id',
            field=models.CharField(blank=True, help_text='Unique non-sequential session token, e.g. A7F3K2', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(default='video', help_text='Consultation mode: video, audio, chat, phone', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='anonymous_session_id',
            field=models.CharField(blank=True, help_text='Unique anonymous identifier e.g. A7F3K2', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='audio_only',
            field=models.BooleanField(default=False, help_text='True if consultation is audio-only without video'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Consultation duration in seconds'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('video', 'Video'), ('audio', 'Audio'), ('phone', 'Phone')], default='chat', max_length=10),
        ),
    ]
